[package]
name = "dh_helper"
version = "0.1.0"
authors = ["Igor Stepanenko <i.stepanenko@osnovalab.ru>"]

[dependencies]
serde = "1.0.70"
serde_derive = "1.0.70"
#serde_json = "1.0"
serde_yaml = "0.7"
